services:
  - type: web
    name: student-performance-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: FRONTEND_ORIGINS
        sync: false
      - key: FRONTEND_BASE_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: MAIL_FROM
        sync: false
