services:
  - type: web
    name: student-performance-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: FRONTEND_ORIGINS
        sync: false
      - key: FRONTEND_BASE_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: MAIL_FROM
        sync: false
