import axios from 'axios';
import type { Recommendation, StudentInput, UncertaintyResult } from '../types';

type ProfileUpdatePayload = Record<string, unknown>;

const API_BASE_URL = import.meta.env.VITE_API_BASE || 'http://127.0.0.1:8000';

const api = axios.create({
  baseURL: API_BASE_URL,
  headers: {
    'Content-Type': 'application/json',
  },
});

api.interceptors.request.use((config) => {
  const token = localStorage.getItem('access_token');
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

function mapPrediction(data: any) {
  return {
    risk_probability: Number(data?.risk_percentage ?? 0),
    risk_band: data?.risk_band ?? 'Moderate',
    confidence: 0,
    key_factors: Array.isArray(data?.explanation)
      ? data.explanation.map((factor: string, index: number) => ({
          factor,
          impact: index + 1,
        }))
      : [],
  };
}

function mapUncertainty(data: any): UncertaintyResult {
  const pointEstimate = Number(data?.risk_probability ?? 0);
  const uncertainty = Number(data?.uncertainty ?? 0);
  return {
    lower_bound: Math.max(0, pointEstimate - uncertainty),
    upper_bound: Math.min(1, pointEstimate + uncertainty),
    point_estimate: pointEstimate,
  };
}

function mapRecommendations(data: any): Recommendation[] {
  const recommendations = Array.isArray(data?.recommendations) ? data.recommendations : [];
  return recommendations.map((item: any, index: number) => ({
    title: String(item?.title ?? `Recommendation ${index + 1}`),
    description: String(item?.description ?? 'Personalized recommendation generated by the model.'),
    impact: item?.impact === 'High impact' || item?.impact === 'Quick win' || item?.impact === 'Long-term'
      ? item.impact
      : 'Quick win',
    category: String(item?.feature ?? 'general'),
    priority: index + 1,
  }));
}

export const apiService = {
  health: () => api.get('/'),

  predict: async (data: StudentInput) => ({ data: mapPrediction((await api.post('/predict', data)).data) }),

  uncertainty: async (data: StudentInput) => ({ data: mapUncertainty((await api.post('/uncertainty', data)).data) }),

  recommend: async (data: StudentInput) => ({ data: mapRecommendations((await api.post('/recommend', data)).data) }),

  signup: (params: { full_name: string; email: string; password: string; role: 'student' | 'teacher' }) =>
    api.post('/auth/signup', params),

  login: (params: { email: string; password: string }) =>
    api.post('/auth/login', params),

  logout: async () => {
    const refreshToken = localStorage.getItem('refresh_token');
    if (refreshToken) {
      try {
        await api.post('/auth/logout', { refresh_token: refreshToken });
      } catch {
        // Best-effort logout
      }
    }
    localStorage.removeItem('access_token');
    localStorage.removeItem('refresh_token');
  },

  getProfile: () => api.get('/auth/me'),

  updateProfile: (_data: ProfileUpdatePayload) =>
    Promise.reject(new Error('Profile updates are not exposed by the current backend API.')),
};

export default api;
